name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ~/portfoliowebsite
            git reset --hard
            git pull origin main
            sudo rm -rf /var/www/html/dist
            sudo cp -r ~/portfoliowebsite/dist /var/www/html/
            sudo chown -R www-data:www-data /var/www/html/dist
            sudo chmod -R 755 /var/www/html/dist
